services:
  storage:
    image: satangtech/explorer-storage:0.0.1
    restart: always
    environment:
      - PORT=5555
      - BIND=0.0.0.0
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./.env:/service-storage/.env
    depends_on:
      - redis

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=Password123!
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 512mb
